steps:
  # Install dependencies
  - name: 'python:3.9-slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov

  # Run tests
  - name: 'python:3.9-slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov
        python -m pytest test_main.py -v --cov=main --cov-report=term

  # Deploy to Cloud Functions
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud functions deploy user-service-${BRANCH_NAME} \
          --runtime python39 \
          --trigger-http \
          --entry-point gcp_handler \
          --memory 256MB \
          --timeout 60s \
          --allow-unauthenticated \
          --region ${_REGION} \
          --set-env-vars ENVIRONMENT=${_ENVIRONMENT} \
          --source .

  # Update traffic allocation (for production)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ "${BRANCH_NAME}" = "main" ]; then
          gcloud functions deploy user-service \
            --runtime python39 \
            --trigger-http \
            --entry-point gcp_handler \
            --memory 256MB \
            --timeout 60s \
            --allow-unauthenticated \
            --region ${_REGION} \
            --set-env-vars ENVIRONMENT=production \
            --source .
        fi

substitutions:
  _REGION: 'us-central1'
  _ENVIRONMENT: 'staging'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  substitution_option: 'ALLOW_LOOSE'

timeout: '1200s'

tags:
  - 'user-service'
  - 'backend'
  - 'cloud-functions'
