version: 0.0
os: linux

files:
  - source: /
    destination: /opt/mono-repo-ui
    overwrite: yes

permissions:
  - object: /opt/mono-repo-ui
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - directory
  - object: /opt/mono-repo-ui/deploy.sh
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - file

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root
  
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: root
  
  ApplicationStart:
    - location: deploy.sh
      timeout: 600
      runas: root
  
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 300
      runas: root
  
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: root
